s3tools/s3cmd

s3cmd
Previous output:
```
$ s3cmd ls
2015-01-13 19:28  s3://bucket
2015-01-13 19:25  s3://bucket3
2015-01-12 20:28  s3://bucket2
```
New output:
```
$ s3cmd ls
2015-01-13 19:28  s3://bucket
2015-01-12 20:28  s3://bucket2
2015-01-13 19:25  s3://bucket3
```
=> Sort s3cmd ls output by bucket name

S3/Config.py, S3/S3.py, s3cmd
Signed-off-by: Dongmao Zhang <deanraccoon@gmail.com>
=> add new option --limit-rate to throttle download/upload speed

s3cmd
Hi,
following there are some debian patches would be nice to have merged upstream.
thanks
=> Debian patches

S3/Config.py
I was able to get 30% better put performance to local S3 endpoint
=> enlarge write and read buffers

s3cmd
As in the title, handy for people operating on  prod buckets
=> Add --dry-run to fixbucket command

S3/S3.py
There is a lot of different "python-magic" libraries/versions, all doing different things, so all cases need to be covered the most efficiently.
file-5.11 test position has be switched with "filemagic" as it should be more commonly used.
Review pf each python magic lib has been done to ensure to use encoding or not only when it is needed.
=> Fixes #528 (UnicodeEncodeError magic). 2nd version

S3/S3.py
This addresses https://github.com/s3tools/s3cmd/issues/577
Signed-off-by: Tim Anderson <tsa@biglakesoftware.com>
=> Error check on multipart upload

INSTALL
I found PIP instructions were in the issue queue. I thought it would be great if there were also in the Install file.
=> Install instructions for PIP

S3/S3.py, s3cmd
Doesn't pass tests yet because it doesn't obey --exclude-* directives
=> iterative du, rm

S3/S3.py
Bug 604 reported that files [put] from stdin, when later [get], print
a warning that the MD5sums do not match.
Files uploaded via multipart upload (either large files, or files read
from stdin) have ETags on their metadata that include '-'.  These are
known to not be the actual md5.  However, the recv_file() path did not
include code to exclude comparing such md5 values with the calculated
value.
Furthermore, this code path is U-G-L-Y and nearly unreadable.  This
attempts to fix that only slightly, in so far as to correct the logic
for ETags with '-' in them, by re-arranging code blocks, changing
variable names to not be overloaded and be more meaningful, and
skipping the calculation of md5 on the received file (including
possibly reading the file back from the file system) when the ETag …
=> fix md5 checks on download of multipart-uploaded files  (#604)

S3/Config.py, S3/Crypto.py, run-tests.py, s3cmd
This allows clients to download with human-friendly names and allows
browsers to properly interpret media like videos.
=> Support signed URL content disposition type

s3cmd
=> Fix for error reporting in case of upload error.

S3/S3.py, S3/Utils.py, run-tests.py, s3cmd
Add detection and handling of different OSErrors like "File name too long."
=> Reworked Upload and Download errors to be more consistent. 

S3/FileLists.py, run-tests.py, s3cmd
This PR fixes local2remote and remote2local sync source and destination inputs handling for all the different cases that could be encountered like a missing source folder.
=> Fixes local2remote and remote2local source and destination inputs

S3/Config.py, S3/FileLists.py, S3/MultiPart.py, S3/Progress.py, S3/S3.py, s3cmd
--Stats only work for the "sync" commands for the moment.
=> Improvement to progress + added the --stats option

S3/ConnMan.py
Supersedes https://github.com/s3tools/s3cmd/pull/668
=> Atodorov ssl wildcard fix

S3/S3.py
=> s3cmd: Fix s3 path style signature v4 handling.

s3cmd.1
--disable have wrong description cc --enable
PR to fix man in 1.x versions of s3cmd
=> FIX: update s3cmd.1 --disable man entry option

S3/S3.py, S3/Utils.py, s3cmd
Add a command to get lifecycle configuration from a bucket.
Signed-off-by: Daniel Gryniewicz <dang@redhat.com>
We are implementing lifecycle in Ceph RadosGW and need this command.
=> Add getlifecycle command

S3/ACL.py, S3/AccessLog.py, S3/S3Uri.py, S3/SortedDict.py, run-tests.py, setup.py
=> Python3: use print function

S3/BidirMap.py, S3/CloudFront.py, S3/Config.py, S3/ConnMan.py, S3/Exceptions.py, S3/FileLists.py, S3/S3.py, S3/Utils.py, run-tests.py, setup.py
=> Python 3: Fix has_key, except, numliterals with 2to3

S3/ConnMan.py
=> Properly passing parsed hostname and port

S3/Config.py, S3/Crypto.py
Hello,
This is just a quick fix to add an configuration option when using sign url to generate an HTTPS link
=> Adding config option for signurl to use https prefix

S3/S3.py
=> Change the marker value for NextMarker in bucket_list_streaming

s3cmd
This avoids the distutils need as runtime dependency
=> Avoid distutils usage at runtime

S3/S3.py
Fixes #491
I would attach a test but I'm struggling to isolate the issue.
Suggestions on how to craft the test are welcomed. 😅
=> Avoid passing 'connection' header to 'modify' requests

S3/Crypto.py
* Fixes glacier restore using V2
=> Add restore subresource to V2 signature

s3cmd
=> Update restore cmd help

s3cmd
=> s3cmd: python 3.8 compat

INSTALL.md
Noticed that someone created a `brew` formula for this and thought it would be nice if it was documented somewhere in the `README.md` or the `INSTALL`. While looking at the `INSTALL`, I realized it wasn't easy to read so i renamed it to `INSTALL.md`
=> README: brew install and renamed to INSTALL.md

S3/Config.py
Closes #1117 .
Fix http call on role endpoint to retrieve the token each time the role_refresh in invoke
=> [#1117] Improve speed when running on EC2 instance

s3cmd
=> Fix deprecation warnings due to invalid escape sequences.

README.md
Adding a quick link to the install instructions since it was not obvious to me that I could just use brew before I downloaded the whole thing and found the install instructions. :)
=> Add link to install.md

S3/ACL.py, s3cmd
=> ACL: when setacl private, revoke public write acl

S3/S3.py
Fixed RestoreRequest namespace according to S3 API: https://docs.aws.amazon.com/AmazonS3/latest/API/API_RestoreObject.html
=> Fixed RestoreRequest XML namespace URL (#1203)

S3/FileLists.py
=> treat 0 byte cache files as nonexistent

S3/Config.py
Hello!
We are trying to disable IMDSv1 across our fleet, to improve our security posture.
(Some background: an explanation of what AWS did, and why, is in [Add defense in depth against open firewalls, reverse proxies, and SSRF vulnerabilities with enhancements to the EC2 Instance Metadata Service](https://aws.amazon.com/blogs/security/defense-in-depth-open-firewalls-reverse-proxies-ssrf-vulnerabilities-ec2-instance-metadata-service/). They also provide a helpful article on how to [Use IMDSv2](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html).)
`s3cmd` had IMDSv1 hard-coded, so it failed on machines where we disabled this feature.
This PR is a (fairly minimal?) change to use IMDSv2. (It would probably be much cleaner to use the AWS-supported …
=> Use IMDSv2 to retrieve instance metadata

S3/S3.py, s3cmd
Sepc for ref:
https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketNotificationConfiguration.html#API_PutBucketNotificationConfiguration_RequestSyntax
https://docs.aws.amazon.com/AmazonS3/latest/userguide/NotificationHowTo.html
=> Add notification commands

.github/workflows/test.yml
Upgrade actions to:
* `actions/checkout@v3`
* `actions/setup-python@v4`
* `actions/cache@v3`
=> Bump GitHub actions

.github/workflows/test.yml, requirements.txt
It will create cache for pip packages based on:
* Runner OS
* Python version
* requirements.txt hash
=> Enable pip cache in actions/setup-python

s3cmd
=> Fix type error(#1313)

S3/S3.py, s3cmd, s3cmd.1
This time the XML is generated by s3cmd
=> Add setobjectretention and setobjectlegalhold commands

s3cmd, s3cmd.1
=> fix: typo in la command help text

.github/workflows/test.yml
=> ci: change python matrix to add 3.13 and use older ubuntu for python3.7
