S3/ConnMan.py
First, the implementation had a bug, and did not actually disable the
ssl.match_hostname() check like we originally believed, because the
change to the context.check_hostname=False flag occurred too late.
Second, we want to do the hostname checking ourselves, so we can
continue when presented with an S3 wildcard certificate.  We invoke
the SSLContext.match_hostname() function for all connections, and if
it fails, we check if we're actually looking at an S3 wildcard
certificate and communicating with an S3 host. If so, this is
permissible.  If not, we fail the connection immediately.
This should resolve the concern over disabling SSL certificate
hostname checking.
=> fix S3 wildcard certificate checking

S3/Utils.py, s3cmd
UNIX timestamps are annoying on the command line, eg. compare:
$ s3cmd signurl s3://bucket/filename $(($(date +%s) + 60))
vs.
$ s3cmd signurl s3://bucket/filename +60
Both times are still relative to the local clock of course, but at least
this is easier to read and play around with.
=> Support relative expiry times in signurl

S3/ACL.py, s3cmd.1
Current --acl-revoke only accepts user canonical ids as grantee specification.
'info' command lists users' display names in ACL entries.
Adding support for display names in --acl-revoke makes it easy to revoke
ACLs based on info command output. This alleviates problem outlined in #223
=> Add support for display names in --acl-revoke (#223)

S3/FileLists.py
Ceph sometime returns
{'status': 200, 'headers': {}, 'reason': '', 'data': ''}
which chokes s3cmd because headers is an empty dictionary.
=> If response['headers'] is empty, then don't update dict.

S3/S3.py, s3cmd
For copy and modify, take care to check if there is an error after the start of the operation (reported by a status 200 but an "Error" root entry in the xml body)
In addition, for the move, It is good to check for the CopyObject xml reply to see if it is a success.
But, if there is a status of 200 and no "data" in response, don't fail. Other S3 server implementations use only status code and don't return any body when there is no error.
References:
http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectCOPY.html
http://doc.s3.amazonaws.com/proposals/copy.html
=> For copy and modify, take care to check if there is an error after the start of the operation

s3cmd
...remote2remote: If there was failed copy, seq number was preserved but previously uploaded file number was forgotten, thus user could have faced an invalid indication like: 14/8 when there is 6 upload following 6 remote copy failures.
=> Fix invalid file transfer progress info in case of local2remote and 

s3cmd
If an IOError occurs due to EPIPE, i.e. writing to a closed pipe, we can ignore it instead of printing the error screen. This makes s3cmd friendlier when used with other tools like `head` or `less`.
Addresses https://github.com/s3tools/s3cmd/issues/549
XXX: Might this be masking more serious errors that could manifest as EPIPE?
=> Fail silently on SIGPIPE

README.md
The documentation explains the difference between (note the trailing slash)
`s3cmd get --recursive s3://public.s3tools.org/somewhere` and `s3cmd get --recursive s3://public.s3tools.org/somewhere/` but then shows the former command as input with the results of the latter command.
=> Fix missing slash in directory semantics documentation

S3/Config.py, s3cmd
I think it's about time that `s3cmd` defaults to HTTPS when communicating with Amazon S3, just like `aws-cli`. I could be wrong, of course, but I don't see any issues by settings this as the default options.
=> Use HTTPS by default

S3/Config.py, S3/ExitCodes.py, s3cmd
Add a configuration option that allows an error return on any transfer
error of a file. This is a config option (stop_on_error)  and a
commandline option (--stop-on-error). The Default is the current
continue behavior. With the option or config setting to True, the
commands (get, put, sync remote2remote, remote2local, or local2remote)
will all return an error status. The Get and Put commands return
EX_PARTIAL where the typical response on sync will be EX_TEMPFAIL but
could be any of:
* EX_SERVERMOVED
* EX_SERVERERROR
* EX_ACCESSDENIED
* EX_NOTFOUND
* EX_CONFLICT
* EX_PRECONDITION
* EX_SERVICE
* EX_SOFTWARE
Signed-off-by: Tim Anderson <tsa@biglakesoftware.com>
=> Add stop_on_error

README.md, S3/Config.py, s3cmd
This fully removes the option and switches its use to stop_on_error.
Also document the new EX_PARTIAL and use of stop_on_error in the README.
Signed-off-by: Tim Anderson <tsa@biglakesoftware.com>
=> Replace ignore_failed_copy with stop_on_error

S3/Config.py, s3cmd
The `cfg.progress_meter` config setting is stomped on by the `isatty()` value. On NT it then complains that the progress meter is not available. This means we get `"Option --progress is not yet supported on MS Windows platform. Assuming --no-progress."` even if we specifically set `--no-progress`
This change makes it so the `isatty()` value is used if neither `--progress` nor `--no-progress` are specified. Otherwise, use the user-provided setting.
=> move progress_meter default setting down to Config class

S3/S3.py, s3cmd
Adds the ability to set, get and del cors policy. Based on the policy commands.
```
> s3cmd setcors test-cors-file s3://example
> s3cmd  info s3://example
s3://example (bucket):
Location:  us-east-1
Payer: BucketOwner
Expiration Rule: none
policy:    none
cors:      <?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><CORSRule><AllowedOrigin>*</AllowedOrigin><AllowedMethod>GET</AllowedMethod><AllowedMethod>POST</AllowedMethod><AllowedMethod>PUT</AllowedMethod><MaxAgeSeconds>3000</MaxAgeSeconds><AllowedHeader>*</AllowedHeader></CORSRule></CORSConfiguration>
ACL:       accounts: READ
ACL:       accounts: WRITE
ACL:       accounts: READ_ACP
ACL:       accounts: WRITE_ACP
> s3cmd delcors s3://example
s3://example/: CORS deleted
> s3cmd …
```
=> Add ability to set, get and del cors policy.

S3/ConnMan.py
We were still checking hostnames in SSL certs when
--no-check-certificate is provided.  This caused self-signed
certificates for S3-like services to fail.
Fixes Bug #612
=> Don't check hostnames in SSL certs when --no-check-certificate (#612)

S3/AccessLog.py
s3cmd accesslog command would throw these warnings:
S3/AccessLog.py:57: FutureWarning: The
behavior of this method will change in future versions.  Use specific
'len(elem)' or 'elem is not None' test instead.
if not le:
S3/AccessLog.py:31: FutureWarning: The
behavior of this method will change in future versions.  Use
specific 'len(elem)' or 'elem is not None' test instead.
return bool(self.tree.find(".//LoggingEnabled"))
Fix these to use 'is not None' or 'is None' instead.
=> Fix FutureWarnings from S3/AccessLog.py

S3/FileLists.py, run-tests.py, s3cmd
Attempt to fix the first bug of issue #600 : When a subfolder "xxx" was selected as source, the sync comparison was done against the destination base whereas it had to be done based on the "xxx" subfolder of the destination.
Original issue:
<<
./s3cmd -c s3cfg sync -vr admin s3://test600/
./s3cmd -c s3cfg sync -vr printing s3://test600/
The second call will try to compare with the content of test600/ instead of with the content of s3://test600/printing/. Thus, if --delete-removed is used, the second call with remove the "admin" folder.
I indeed think that it is a bug.
>>
Now the correct behavior is the following:
<<
- The source path is either like "/myPath/my_src_folder" and
the user want to upload this single folder and optionally only delete
things that have been removed inside this …
=> Fix for first issue of #600  (sync folder with themselves and not with destination base)

S3/Config.py, S3/S3.py, s3cmd
This allows us to use the newly announced STANDARD_IA class, as well
as STANDARD or REDUCED_REDUNDANCY.  This effectively deprecates
--[no-]reduced-redundancy options.  If both are specified,
--storage-class wins.
If the user specifes an invalid class, they will get an error:
S3 error: 400 (InvalidStorageClass): The storage class you specified
is not valid
=> add --storage-class option

S3/Config.py, S3/S3.py
Can use KMS to manage encryption keys for S3
=> basic SSE-KMS support

S3/S3.py
The `recv_file` would drop the start_position if it needed to pass the request to 400 or 403 fallback handlers.
=> Fix for #634. Partial get start position was dropped

S3/S3.py
Needed for copying content from requester-pays buckets into other
buckets.
=> Allow --requester-pays for PUT commands too (#585)

S3/FileLists.py
I think it should be warned if skipping non-existing local files.
And it's much the same for symbolic links.
=> Warn when skipping non-existing files or symbolic links

s3cmd
While restoring recursively, ignore RestoreAlreadyInProgress exception to continue restoring other items.
=> Ignore RestoreAlreadyInProgress exception on restore command

S3/ConnMan.py
In RHEL 7.2 python-libs-2.7.5-34.el7.x86_64 introduced the following change:
```
diff -u httplib.py /usr/lib64/python2.7/httplib.py
--- httplib.py	2014-02-11 14:46:38.000000000 +0200
+++ /usr/lib64/python2.7/httplib.py	2015-11-24 16:33:57.106008991 +0200
@@ -215,6 +215,10 @@
_MAXLINE = 65536
+# maximum amount of headers accepted
+_MAXHEADERS = 100
+
+
class HTTPMessage(mimetools.Message):
def addheader(self, key, value):
@@ -271,6 +275,8 @@
elif self.seekable:
tell = self.fp.tell
while True:
+            if len(hlist) > _MAXHEADERS:
+                raise HTTPException("got more than %d headers" % _MAXHEADERS)
if tell:
try:
startofline = tell()
@@ -1159,21 +1165,44 @@
def __init__(self, host, port=None, key_file=None, cert_file=None,
strict=None, timeout=socket._GLOBAL_DEFAULT_TIMEOUT,
- …
```
=> Disable hostname checks for SSL connections on RHEL 7.2

S3/Config.py, S3/MultiPart.py, S3/S3.py
I found the issue described here
http://sourceforge.net/p/s3tools/discussion/618865/thread/3b563258/
and have written a simple patch that avoids the unnecessary upload of a file that will fail later after a lot of wasted time and bandwidth.
PS: It is my first Python code and my first Git pull request. HTH.
=> Avoid attempting a multipart upload with more than 10000 parts

S3/Config.py, s3cmd
Normally acl_public = None and it's not present, nor read from,
the config file.  If a user wants to set it in the config file though,
we need to be able to read it from the config file.
We also need to _not_ have the lack of command line options
unintentionally set it back to None.
Add special handling for acl_public, when reading in the
config file, and when handling --acl-public and --acl-private options.
=> Allow acl_public = True/False to be in config file #606

Makefile
Currently, the Makefile has a hard-coded version number. If you run "make git-rpm" without editing the Makefile, the RPM version may not be the same the s3cmd version. However, it is easy to allow the Makefile to extract the version from the PkgInfo.py file.
=> Let Makefile determine version number from PkgInfo.py file

S3/CloudFront.py, s3cmd
Add support for invalidating multiple CF distributions with  --cf-inval when the bucket is the origin for multiple distributions
=> Invalidate multiple CF distributions when necessary

S3/S3.py, s3cmd
If 'etag' is missing do not crash 's3cmd',  throw a warning and handle it gracefully.
=> Missing etag in HTTP headers, handle gracefully.

setup.py
Issue:
```
$ python setup.py
Traceback (most recent call last):
File "setup.py", line 42, in <module>
if sys.argv[1] == "sdist":
IndexError: list index out of range
```
This can be avoided and should print help without any arguments.
=> build: Do not throw exceptions if no arguments were passed for setup.py

s3cmd
If you try downloading file with -q and destination is -, you'll receive such errors:
```
s3cmd -q get s3://some-bucket/somefile - > /dev/null
WARNING: Retrying failed request: somefile (I/O operation on closed file)
```
I do not think it is actually very good solution, actually all logging should be done through some logging wrapper, this way there won't be a need to mangle with stdout...
=> Do not close stdout, it might be used when file is downloaded

S3/S3.py
S3 occasionally closes our connection unexpectedly.  We weren't
catching this, but would crash with a traceback when it happens.
Explicitly catch and retry on ECONNRESET.
=> Catch 'connection reset by peer' (errno 104) and retry

s3cmd
Some implementations such as S3Proxy with the B2 backend do not return
ETag.
=> Handle missing ETag in subcmd_bucket_list

S3/ConnMan.py
As the issue of wildcard certificate matching failures for DNS-style bucket names (i.e. those which contain the `.` character) also expresses itself for other S3-compatible services, the code that checks specifically for `amazonaws.com` has been replaced with a more general approach that checks for the `.` character.
Refs #437.
=> Generalize wildcard certificate forgiveness

S3/S3.py
Proxy SSL/HTTPS requests use regular relative URIs, while only HTTP requests use absolute URIs
=> Change proxy SSL URI to relative

S3/Config.py, S3/S3.py, s3cmd
Currently "ls" command returns all objects within a bucket under a certain prefix using the delimiter '/' and there seems to be no option to limit the number of returned objects. If the contents of the main folder or a sub-folder is huge, it will continue to list all objects until it finishes. Its possible to take time to finish it and it could be overloaded the S3 server side.
This change is to add "max-ls-keys" option to "ls" command to return the specified number of objects instead of returning all objects.
=> add "limit" option to "ls" and "la" commands to return the specified number of objects instead of returning all objects.

S3/ConnMan.py, S3/S3.py
This changes allows user to set path to S3 api instead of default '/'. It will enable s3cmd to work with s3ninja or custom s3-ceph endpoints.
=> Support for custom S3 api path

s3cmd
Currently, if user wants to use an S3 endpoint rather than Amazon S3 default region endpoint, the following entries need to be updated manually after the first configuration using "--configure".
This change is to enable to configure "host_base" as "S3 endpoint" in the first interactive configuration and update "host_bucket" as well so that user can use this command without any changes after the first configuration.
[.s3cfg]
host_base = s3.amazonaws.com
host_bucket = %(bucket)s.s3.amazonaws.com
=> Enable to configure "host_base" as "S3 Endpoint" in

S3/FileDict.py
`s3cmd sync` was found to be misbehaving with ceph v0.94.2. It was due to a bug in radosgw that returned empty ETags. http://tracker.ceph.com/issues/12955. This PR handles such cases with empty ETags.
=> fix: handle empty md5 in find_md5_one

.travis.yml, S3/ACL.py, S3/AccessLog.py, S3/CloudFront.py, S3/ConnMan.py, S3/Crypto.py, S3/Exceptions.py, S3/FileDict.py, S3/FileLists.py, S3/HashCache.py, S3/MultiPart.py, S3/S3.py, S3/S3Uri.py, S3/SortedDict.py, run-tests-minio.py
Continue the effort for making it Python 3 compatible.
Some modules (Config, Utils, Progress) have cyclic dependency which makes it difficult to remove their implicit imports.
To keep this PR minimal, I do not attempt to resolve the above issue this time.
=> Python3: make relative imports explicit

README.md, S3/Config.py, S3/S3.py, s3cmd, s3cmd.1
Users can now specify whether they want their S3 Glacier retrieval to be costly and quick or slow and cheap.
=> Added support for S3 Glacier archive retrieval speed options

S3/Config.py, S3/ConnMan.py, S3/Crypto.py, S3/Exceptions.py, S3/HashCache.py, S3/Progress.py, S3/S3.py, S3/Utils.py, run-tests-minio.py, run-tests.py, s3cmd
Continue the effort for making s3cmd Python 3 compatible.
- Remove remaining implicit relative imports
I thought about removing the circular dependencies, but in the end I decided to simply modify the imports to minimize changes.
- Fix some imports that have different names in Python 3.
- Run 2to3 on s3cmd to fix several compatibility issues
=> Python3: fix several imports, and run 2to3 on s3cmd

run-tests.py
If you're running single tests, they will fail on test 15 because the testsuite-out dir isn't created.
=> Ensure testsuite-out is created before running dd

S3/S3.py
See: https://github.com/s3tools/s3cmd/issues/849
“After you configure a bucket to be a Requester Pays bucket, requesters must include x-amz-request-payer in their requests either in the header, for POST, GET and **HEAD** requests, or as a parameter in a REST request to show that they understand that they will be charged for the request and the data download.”
http://docs.aws.amazon.com/AmazonS3/latest/dev/RequesterPaysBuckets.html
=> Fixes #849 by adding requester pays header to HEAD requests

run-tests-minio.py, run-tests.py, s3cmd
When trying to cp/mv multiple files, make sure the destination
has a trailing slash so it is treated as a directory. Otherwise,
multiple files can get moved to a single file, leading to data
loss.
=> address issue #854 : don't allow mv/cp of multiple files to single file

S3/S3.py
Fixes https://github.com/s3tools/s3cmd/issues/880
=> Don't need to compute ETag md5sum match if it is not a real md5sum

S3/CloudFront.py
Fixes bug in cinvalinfo when only one path is supplied. Before it displayed the nr of characters in the string instead of "nr of paths: 1".
=> Fixes bug in cinvalinfo when only one path is supplied to cloudfront invalidation request.

S3/ACL.py
Grantee.display_name may not be initialize for some Grantee types,
most notably for xsi:type="Group".
However, tolower() is called on this attribute in ACL.revoke(),
raising unhandled AttributeError. To prevent it, let's change
default value of Grantee.display_name to empty string with almost
identical semantical value, but allowing lower() call to succeed.
I also applied the Boolean Distributive law to simplify condition
in ACL.revoke().
=> Fixes #936 - Fix setacl command exception

S3/Config.py
The `files` variable has a type of `bytes()` in Python 3.
For example, if `files = b'master'` then the request path would be formatted as
`"/latest/meta-data/iam/security-credentials/b'master'"`
The `.decode()` method converts a bytes into a proper string in Python 3 and doesn't change anything in Python 2.
=> Fix Python 3 bytes string encoding when getting IAM credentials

S3/Config.py
Commit bc38c2a879305ffd3cdd4f025f4161b430e79150 added the ability to set
acl_public from the config file -- but it did not take into account that
it is a 'tri-state' value so the string is what is written, causing it
to ALWAYS be true.
This results in unexpected and insecure behavior if 'acl_public = False'
is used in the config file.
This patch modifies the Config.update_option to check the option type
AND the value if the original is None. If an option's default is None
and the value is a bool (true, false, yes, no, 0, 1) then it will set it
to a bool value.
=> Fix handling of config tri-state bool values (like acl_public)

S3/ACL.py
display_name is None for the grantee corresponding to public access;
name is 'http://acs.amazonaws.com/groups/global/AllUsers'.
So if you try and grant full_control to a user on an object which is
public, the check at line 189 fails thus:
```python
self.grantees = [g for g in self.grantees if not (g.name.lower() == name or g.display_name.lower() == name)]
AttributeError: 'NoneType' object has no attribute 'lower'
```
because g.display_name is None
This patch fixes this by checking for not-None before calling lower()
Signed-off-by: Matthew Vernon <mv3@sanger.ac.uk>
=> Allow setting full_control on objects with public read access

S3/Utils.py
Fixing proper handling of file sizes. Will correctly return floating point or integer as appropriate.
Previous version appeared to rely on integer division as implemented in py2 and would return a float regardless of flating_point argument in py3.
=> Fix for proper handling of int and float file sizes

S3/S3.py
In-case of Minio which can support any arbitrary region names,
users might set the region with uppercase value which seems
to have been lowercased during make bucket. In-fact the
signature region scope is never lowercased - this creates
and inconsistent behavior.
Make bucket location constraint
```
DEBUG: bucket_location: <CreateBucketConfiguration><LocationConstraint>zzz</LocationConstraint></CreateBucketConfiguration>
```
Signature V4 headers
```
DEBUG: signature-v4 headers: {'x-amz-content-sha256': u'a70e963f9ce55e14adcaf0c3f9aae558bcd8b2d4bedd7f3f193a8b853640d5c2', 'Authorization': u'AWS4-HMAC-SHA256 Credential=minio/20180807/zzz/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date,Signature=5a797cc1744abaa86a7a882c801ba0a35fb046dcddc93456871f9f5d49dec1e1', 'x-amz-date': …
```
=> Do not convert all regions to lower case

S3/S3.py
This patch allows cmd_info to work properly in case of getting any unicode chars in reply to bucket Policy/CORS requests.
Fixes at least #847
=> Return decoded response in get_policy and get_cors

S3/Config.py, S3/S3Uri.py
If public_url_use_https is true, prefix public URLs with https. Otherwise use
http as before.
=> Configurable public URL protocol

S3/Custom_httplib27.py, S3/Custom_httplib3x.py
=> Fix simple typo: unecessarily -> unnecessarily

S3/Crypto.py
When check_bucket_name_dns_support returns False, format the url
for path-style bucket access (related to https://github.com/s3tools/s3cmd/pull/416).
=> Fix signurl to support path-style bucket access via check_bucket_name_dns_support

run-tests.py
This fixes issue #1066.
Tested on Python 2.7.17, 3.8.1, and 3.7.6 via run-tests.py - All tests pass.
While it would be possible to fix this simply by changing the "Autotest-3" to "autotest-3", using pbucket() should help reduce the chances of something like this happening in the future.
=> Changed "Buckets list" test to use pbucket rather than hardcoded names.

.gitignore, run-tests.docker.README.md, run-tests.dockerfile
I'm using this for my testing, and figured it might be useful to other contributors.  At the core, this is just a Dockerfile which will set up an environment to execute run-tests.py.  Because it pulls Python images from Docker Hub, versions of Python can be used that aren't easily accessible to the contributor in other ways.
Note that a valid .s3cfg needs to be copied into the project directory, since Docker cannot copy files from outside it's "context" directory.  For this reason, ".s3cfg" has been added to the .gitignore.
Instructions are in run-tests.docker.README.md, but are copied in here for easy reference and questions if needed.
* `docker build -t s3cmd-tests --build-arg pyVersion=3.6 -f run-tests.dockerfile .` - Note the trailing period and substitute your desired Python version …
=> Feature: Allow use of Docker to run test cases with multiple Python versions

S3/S3.py
With this commit 4 years ago OSError was caught:
https://github.com/s3tools/s3cmd/commit/889c5a7ba1ef8fc48f0c1be593e7ddf1e518a408
Looks like there wasn't a good reason to include it give the comment. Also now with python 3 http.client.RemoteDisconnected is getting caught by OSError.
I see @fviard tried to make a fix for RemoteDisconnected here:
https://github.com/s3tools/s3cmd/commit/b4f1424a18a3231230e6c5676d88cd68aa24feba
but the problem persisted until I removed these lines.  There may be other places in the code that have the same issue but this fixed my specific issues with recv_file():
```Traceback (most recent call last):
File "/usr/bin/s3cmd", line 1316, in _download
response = s3.object_get(uri, dst_stream, dst_file, extra_label = seq_label)
http_response = conn.c.getresponse() …
```
=> Fix http.client.RemoteDisconnected errors

S3/HashCache.py, run-tests.py
Fix for Issue #945 
Apologies for the delay, but here's the discussed fix for the issue.
Also added test cases to run-tests.py for the issue and fix.  It essentially:
* Modifies the first sync test to use a cache-file.  This in-and-of-itself should have no bearing on the success or failure of that particular test; it just sets things up for the following two steps.  The cache file is created in a new subdirectory of testsuite, so that it can be removed afterwards without impacting subsequent tests.
* Creates a file that didn't exist during the first sync.  This is also done in the new subdirectory of testsuite.
* Syncs again, confirming that the file was synced.
* Removes that file and does another sync.  This is the step that would have generated a condition causing the "dictionary …
=> Fix for Issue #945 ("RuntimeError: dictionary changed size during iteration" when using cache-file)

S3/Config.py
Update of #1117
Fix timezone on python version 2.7 and 2.6. Old python version don't have `datetime.timezone.utc()` function
=> #1117 Fix timezone on old python version

s3cmd
The wiki title and therefore its URL changed a few months ago, but the error message still points to the old URL.
=> Update wiki URL in error message

S3/Exceptions.py, S3/Utils.py
`getchildren()` method was removed from the `ElementTree` and `Element` classes in Python 3.9. This PR uses built-in `iter()` and `list()` methods instead of the removed one. This fix was suggested in the Python 3.9 release notes:
https://docs.python.org/3.9/whatsnew/3.9.html#removed
I verified this fix on Fedora 33 with Python 3.9.0rc2 by:
```
s3cmd --acl-public sync . s3://...
```
=> fix compatibility with Python 3.9

s3cmd
Make the handling of the two opposite options symmetric.
=> s3cmd: cleanup check_md5 handling a bit

S3/Crypto.py, S3/S3.py
`encodestring()` method was removed from base64 in Python 3.9.
See the release notes:  https://docs.python.org/3.9/whatsnew/3.9.html#removed
=> Update base64.encodestring for Python 3.9 compatibility

s3cmd, s3cmd.1
I've updated descriptions of `sync` command and `--no-delete-removed` option and regenerated `s3cmd.1`.
Added remote to remote synchronization params for `sync` according to this code:
https://github.com/s3tools/s3cmd/blob/55597d16937085be3fc8894f23d958241a9aad9f/s3cmd#L1945-L1946
And `--no-delete-removed` can be used only for `sync`.
=> Change info of sync command and --no-delete-removed option

s3cmd
configured a bucket lifecycle using the filter element:
```
<?xml version="1.0" ?>
<LifecycleConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<Rule>
<ID>Rule2</ID>
<Filter>
<Tag>
<Key>test2</Key>
<Value>test2</Value>
</Tag>
</Filter>
<Status>Enabled</Status>
<NoncurrentVersionTransition>
<NoncurrentDays>3</NoncurrentDays>
<StorageClass>GLACIER</StorageClass>
</NoncurrentVersionTransition>
</Rule>
</LifecycleConfiguration>
```
`s3cmd info` failed because there's no Prefix:
```
File "/usr/bin/s3cmd", line 958, in cmd_info
expiration_desc += "objects with key prefix '" + expiration['prefix'] + "' "
TypeError: cannot concatenate 'str' and 'NoneType' objects
```
Bypass this failure even if s3cmd doesn't support https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetBucketLifecycle …
=> fix get bucket info failed when LC use the filter element

s3cmd.1
Sync by default preserves the file permissions, uid, gid and username in the `x-amz-meta-s3cmd-attrs` meta data field. 
This change documents that. Especially since a lot of people are surprised by this default. 
There was some discussion about this in: https://github.com/s3tools/s3cmd/issues/67
=> Add info about sync defaults

S3/S3.py, s3cmd
In the Cloudian Hyperstore S3 software stack (www.cloudian.com) bucket creation can take an extra header to specify a storage policy id.
`s3cmd mb` silently ignores custom headers as specified with the `--add-header` option.
s3cmd and S3/S3.py updated to pass custom header to the S3 stack.
=> Fixes s3cmd#1197 - add custom header for s3cmd mb

setup.py
Updated `setup.py` to list 3.9 and 3.10 (3.10 is passing the test suite so I assume it works fine)
=> List support of Python 3.9 and 3.10

S3/Config.py
This fixes the issue where the sts endpoint sts.amazonaws.com is not
accessible.
Take into account the environment varialbe AWS_STS_REGIONAL_ENDPOINTS
If the AWS_STS_REGIONAL_ENDPOINTS variable is provided check for AWS_REGION env var to decide
region.
If AWS_REGION is not provided use the same region as the bucket.
(bucket_location parameter)
=> Take into account the AWS_STS_REGIONAL_ENDPOINTS

S3/FileLists.py, run-tests.py
I found out that `--ecxlude dir/` does not work properly on my system (Ubuntu 18.04 + python3.8) since it does not prevent from recursive scanning of all files inside excluded directory, which makes backuping big filesystems completely impossible. 
Here is why it happens:
see https://docs.python.org/3.5/library/fnmatch.html
```
>>> regex = fnmatch.translate('*.txt')
>>> regex
'.*\\.txt\\Z(?ms)'
```
compare with https://docs.python.org/3.6/library/fnmatch.html 
```
>>> regex = fnmatch.translate('*.txt')
>>> regex
'(?s:.*\\.txt)\\Z'
```
This change produces new regexp pattern for `--exclude dir/` which was not handled in FileLists.handle_exclude_include_walk_dir().
It's clear that program is broken and current behaviour is not expected:
1) function FileLists.handle_exclude_include_walk_dir …
=> bugfix: --exclude dir/ walks inside dir/ for python 3.6+

.ci.s3cfg, S3/Config.py, S3/S3.py, s3cmd
As discussed in [this issue](https://github.com/s3tools/s3cmd/issues/1269)
=> list-objects-*: implement allow unordered option

S3/BaseUtils.py, S3/S3.py, S3/Utils.py
When FIPS mode is enabled, s3cmd raises a ValueError exception with the message 'digital envelope routines: EVP_DigestInit_ex] disabled for FIPS' (see below). This change will make s3cmd compatible with FIPS mode.
```
$ fips-mode-setup --check
FIPS mode is enabled.
$ s3cmd put ...
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
An unexpected error has occurred.
...
Problem: <class 'ValueError: [digital envelope routines: EVP_DigestInit_ex] disabled for FIPS
S3cmd:   2.2.0
python:   3.6.8 (default, Jan 19 2022, 23:28:49) 
[GCC 8.5.0 20210514 (Red Hat 8.5.0-7)]
environment LANG=en_US.UTF-8
Traceback (most recent call last):
File "./s3cmd/s3cmd", line 3209, in <module>
rc = main()
File "./s3cmd/s3cmd", line 3106, in main
rc = cmd_func(args)
File "./s3cmd/s3cmd", line 392, in cmd_object_put …
```
=> Add FIPS support

S3/Config.py, S3/S3.py, s3cmd
According to AWS spec for PutBucketNotificationConfiguration API, 
```
x-amz-skip-destination-validation
Skips validation of Amazon SQS, Amazon SNS, and AWS Lambda destinations. True or false value.
```
https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketNotificationConfiguration.html#AmazonS3-PutBucketNotificationConfiguration-request-header-SkipDestinationValidation
=> add `--skip-destination-validation` option for `setnotification`

S3/S3.py
Currently, if s3cmd is used to list objects in bucket, and if only CommonPrefixes are returned, the cli will ignore the NextMarker field and will use the last given prefix.
This fix will consider using the NextMarker if it's present, and will fallback on the last given prefix in both cases. Copying the workflow of awscli
=> fix: Use NextMarker if only prefixes are returned

S3/S3.py
Batch delete fails to return a response object so callers cannot detect failures
=> Add missing return

s3cmd
Currently, if you only specify a bucket:
```
s3cmd abortmp s3://mybucket multipartid
```
Then the request will look like:
```
DELETE /mybucket/?uploadId=multipartid
```
In the case of `AWS` this isn't a huge deal:
```
ERROR: S3 error: 400 (InvalidRequest): A key must be specified
```
However, `ceph` interprets this as a delete **bucket** request not an **abortmp** request. If there are any regular objects in the bucket you get:
```
ERROR: S3 error: 409 (BucketNotEmpty)
```
But if all you have are incomplete multiparts then `ceph` **actually deletes the bucket**.
I intend to open a bug with ceph as well, but since `s3cmd` isn't following the S3 API spec I still think this PR is useful:
https://docs.aws.amazon.com/AmazonS3/latest/API/API_AbortMultipartUpload.html
Let me know if there's a …
=> bug: require object in abortmp

S3/Config.py, S3/S3.py, s3cmd
- Command added
- ~Enable versioning: `s3cmd setversioning s3://mybucket`~
- ~Suspend versioning: `s3cmd setversioning s3://mybucket --versioning-suspended`~
- Enable versioning: `s3cmd setversioning s3://mybucket enable`
- Suspend versioning: `s3cmd setversioning s3://mybucket disable`
- Add versioning status to command `info`
```
$ s3cmd info s3://mybucket
...
Location:  us-east-1
Payer:     BucketOwner
Versioning:Suspended
Expiration Rule: none
Policy:    none
...
```
Resolve #937
=> Support versioning configuration

S3/S3.py
When trying to enable versioning, I was surprised to get the following error:
```
gavin@GAVIN-IDEAPAD-5A75N8AU:/mnt/c/Users/gavin/source/repos/py-s3fs$ s3cmd setversioning s3://gavins3fstesting enable
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
An unexpected error has occurred.
Please try reproducing the error using
the latest s3cmd code from the git master
branch found at:
https://github.com/s3tools/s3cmd
and have a look at the known issues list:
https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions-(FAQ)
If the error persists, please report the
following lines (removing any private
info as necessary) to:
s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Invoked as: /home/gavin/bin/s3cmd setversioning s3://gavins3fstesting enable
Problem: …
```
=> Fix versioning

S3/S3.py
`s3cmd modify s3://myr2/photo.jpg`
> ERROR: Copy failed for: 's3://myr2/photo.jpg' (403 (SignatureDoesNotMatch): The request signature we calculated does not match the signature you provided. Check your secret access key and signing method. )
It happens because `s3cmd` is copying `cf-ray` header and using it for the signature.
A simple fix is to add cf-ray on the `_sanitize_headers` list.
=> fix #1332 SignatureDoesNotMatch error when modifying an object on Cloudflare R2

run-tests.py
`run-tests.py` passes `-include` to curl, which curl interprets as
`--include --netrc --cookie-jar lude`.  Pass `--include` instead.
=> Pass --include to curl

S3/Crypto.py, S3/S3.py, s3cmd
Support Put/Get/DeleteBucketTagging & Put/Get/DeleteObjectTagging ( resolve #911 )
AWS Spec Ref
- https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketTagging.html
- https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObjectTagging.html
=> Support bucket/object tagging command

s3cmd
When restoring a complete bucket stop and raise an error only when the configuration is set to stop on the first error. otherwise keep trying to restore the next objects.
closes #1369
=> Improve recursive object restore

S3/FileLists.py, S3/S3Uri.py
Hi,
Similar to the regex escaping issues reported in #1351, it looks like there are still a few invalid escape sequences in `S3Uri.py` and `FileLists.py` in `s3cmd` version 2.4.0.
I saw these warnings while uploading a file:
```
/usr/local/Cellar/s3cmd/2.4.0_1/libexec/lib/python3.12/site-packages/S3/S3Uri.py:122: SyntaxWarning: invalid escape sequence '\.'
m = re.match("(.*\.)?s3(?:\-[^\.]*)?(?:\.dualstack)?(?:\.[^\.]*)?\.amazonaws\.com(?:\.cn)?$",
/usr/local/Cellar/s3cmd/2.4.0_1/libexec/lib/python3.12/site-packages/S3/S3Uri.py:173: SyntaxWarning: invalid escape sequence '\w'
_re = re.compile("^(\w+://)?(.*)", re.UNICODE)
/usr/local/Cellar/s3cmd/2.4.0_1/libexec/lib/python3.12/site-packages/S3/FileLists.py:525: SyntaxWarning: invalid escape sequence '\*'
wildcard_split_result = …
```
=> cleanup: fixes regex escape warnings in S3Uri.py, FileLists.py

S3/S3.py
Correct typo in error message in S3._http_400_handler method of the `S3/S3.py` file.
fixes #1379
=> Correct typo in error msg in S3._http_400_handler() #1379

S3/S3.py
Hi!
I have issues with the flag `--add-encoding-exts=js,html,css` when uploads js static on production buckets. My files have names like `widget-no-csr.oWiXNN3Poy.js` or `widget-no-csr.oWiXNN3Poy.js.gz`, where is more than one dot symbol separator. Because https://github.com/s3tools/s3cmd/blob/10aea0918082ea87723a7e6754133283883bcfa7/S3/S3.py#L736 there is file extension `oWiXNN3Poy` for first file and `js` for second. That looks like a bug. I fixed that, but I think it could be kind of dangerous because it breaks backward compability.
=> Fix file extension detection for files with multiple dot separators

S3/Config.py
Fixes #1385
This PR allows blank but not null secret_keys provided by command-line switch to also override config file.
=> fix: allow blank secret key

S3/Config.py
Fixes:
- https://github.com/s3tools/s3cmd/issues/1361
- https://github.com/s3tools/s3cmd/issues/1027
Should be OK to replace the removed API call, since the replacement was added in python 3.2.
https://docs.python.org/3/library/configparser.html
=> Fixes #1361 and #1027 - update to python 3.2+ API (existing code calls removed API)

S3/Config.py
By having modifiable environment variable, it is possible to perform authentication with storage solutions that implement Security Token Service (STS) and S3 API.
=> Environment Variable For STS Endpoint 
